name = "Hordcoin"
uuid = "5495aede-444c-4b33-a3d8-b01a3ffd757a"
authors = ["Jakub Kislinger", "Giulio Tani Raffaelli", "Tomáš Kroupa", "Jaroslav Hlinka"]
version = "1.1.0"

[deps]
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.11.8"
CDDLib = "0.10.2"
Combinatorics = "1.1.0"
Ipopt = "1.14.0"
JuMP = "1.29.4"
MAT = "0.11.4"
MadNLP = "0.8.12"
MathOptInterface = "1.49.0"
Mosek = "11.0.1"
MosekTools = "0.15.10"
Polyhedra = "0.8.1"
ProgressMeter = "1.11.0"
SCS = "2.6.0"