name = "EntropyMaximisation"
uuid = "e9d4d5d4-4cae-48c5-8e91-69bea3101049"
authors = ["Jakub Kislinger"]
version = "1.0.0-DEV"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"

[compat]
julia = "1.9"
